- project:
    check:
      jobs:
        - linters:
            vars:
              linters:
                - coala
    gate:
      jobs:
        - linters

    release:
      jobs:
        - build-python-release
        - python-upload-pypi:
            secrets:
              - name: pypi_info
                secret: pypi_test_goern

