- project:
    check:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
    gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"

    post:
      jobs:
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-core-test"
              buildConfigName: "user-api"
        - "trigger-build":
            vars:
              cluster: "pass.psi.redhat.com"
              namespace: "thoth-core-test"
              buildConfigName: "management-api"

    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
