- project:
    check:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
        - "thoth-timeout-test"
    gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"

    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"

- job:
    name: "thoth-timeout-test"
    parent: "base-openshift-pod"
    nodeset:
      nodes:
        - name: "pod"
          label: linter-pod
    run: timeout.yaml
