- project:
    check:
      jobs:
        - thoth-coala
        - thoth-pytest
    gate:
      jobs:
        - thoth-coala
        - thoth-pytest
    release:
      jobs:
        - upload-test-pypi

    kebechet-auto-gate:
      jobs:
        - thoth-coala
        - thoth-pytest

- job:
    name: thoth-pylint-dev
    parent: base-openshift-pod
    nodeset:
      nodes:
        - name: pod
          label: linter-pod
    run: pylint.yaml

- job:
    name: thoth-coala-dev
    parent: base-openshift-pod
    nodeset:
      nodes:
        - name: pod
          label: coala-pod
    run: coala.yaml
