- project:
    check:
      queue: "thoth-station/core"
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
    gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
    release:
      jobs:
        - "upload-test-pypi"

    kebechet-auto-gate:
      jobs:
        - "thoth-coala"
        - "thoth-pytest"
