- project:
    check:
      jobs:
        - linter-job
    gate:
      jobs:
        - noop

    release:
      jobs:
        - upload-test-pypi

    kebechet-auto-gate:
      jobs:
        - noop

# Test openshiftpods provider running in a shared project with regular sa
- job:
    name: linter-job
    parent: base-openshift-pod
    nodeset:
      nodes:
        - name: pod
          label: linter-pod
    run: test.yaml
