- project:
    check:
      jobs:
        - thoth-coala
        - thoth-pylint
    gate:
      jobs:
        - noop

    release:
      jobs:
        - upload-test-pypi

    kebechet-auto-gate:
      jobs:
        - noop

- job:
    name: thoth-pylint
    parent: base-openshift-pod
    nodeset:
      nodes:
        - name: pod
          label: linter-pod
    run: pylint.yaml

- job:
    name: thoth-coala
    parent: base-openshift-pod
    nodeset:
      nodes:
        - name: pod
          label: coala-pod
    run: coala.yaml
